name: booking-order-app
services:
  order-service:
    container_name: order-service 
    # image: yehezkiel08/user-service:1 # change this to your image name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_NAME=order_service
    env_file:
      - .env