name: booking-order-app
services:
  payment-service:
    container_name: payment-service 
    # image: yehezkiel08/user-service:1 # change this to your image name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_NAME=payment_service
    env_file:
      - .env