name: booking-order-app
services:
  field-service:
    container_name: field-service 
    # image: yehezkiel08/user-service:1 # change this to your image name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_NAME=field_service
    env_file:
      - .env