name: booking-order-app # change this to your app name
services:
  user-service: # change this to your service name
    container_name: user-service # change this to your service name
    # image: yehezkiel08/user-service:1 # change this to your image name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # change this to your port
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_NAME=user_service
    env_file:
      - .env